services:
    mapp.example.cron.task.sample:
        class: mapp\example\cron\task\sample
        arguments:
            - '@config'
            - '@log'
        calls:
            - [set_name, [cron.task.mapp.example.sample]]
        tags:
            - { name: cron.task }
